name: Build and Push Docker Image

on:
  push:
    # branches: [ main ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package.json
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          
      - name: Install dependencies with workaround for npm bug
        run: |
          # Handle backend dependencies
          cd backend
          go mod download
          cd ..
          
          # Handle frontend dependencies with the workaround for npm bug #4828
          cd frontend
          # Remove package-lock.json and node_modules as suggested in the error message
          rm -rf package-lock.json node_modules
          # Use npm install rather than npm ci to generate a fresh package-lock
          npm install
          cd ..
        
      - name: Build frontend
        run: make build-frontend
        env:
          HOST_DOMAIN: quixit.us
          HOST_PORT: 3000
          BYPASS_TIME_WINDOWS: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            HOST_DOMAIN=quixit.us
            HOST_PORT=3000
            BYPASS_TIME_WINDOWS=false
          cache-from: |
            type=gha
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=gha,mode=max
            type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: |
            ghcr.io/${{ github.repository_owner }}/quixit:latest
            ghcr.io/${{ github.repository_owner }}/quixit:${{ github.sha }}
            
      # Move cache to prevent cache growth
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache 